---
abstract: 'A Simpler interface to WWW::Curl'
author:
  - 'Andreas Marienborg <andremar@cpan.org>'
generated_by: 'Dist::Zilla version 1.093400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Curl-Simple
requires:
  Benchmark: 0
  Benchmark::Apps: 0
  Carp: 0
  ExtUtils::MakeMaker: 0
  File::Basename: 0
  HTTP::Request: 0
  HTTP::Response: 0
  LWP::Simple: 0
  Moose: 0
  Scalar::Util: 0
  Test::Exception: 0
  Test::More: 0
  WWW::Curl::Easy: 0
  WWW::Curl::Multi: 0
  base: 0
  namespace::clean: 0
resources:
  repository: http://github.com/omega/www-curl-simple
version: 0.100160
